object NotificationCommand "servicenow-service-notification" {
  command = [ "/usr/share/icingaweb2/bin/icingacli", "servicenow", "send", "notification" ]

  arguments += {
    "--service" = {
      required = true
      value = "$notification_servicename$"
    }
    "--host" = {
      required = true
      value = "$notification_hostname$"
    }
    "--output" = {
      required = true
      value = "$notification_serviceoutput$"
    }
    "--state" = {
      required = true
      value = "$notification_servicestate$"
    }
    "--type" = {
      required = true
      value = "$notification_type$"
    }
    "--template" = {
       value = "$snow_template$"
    }
    "--name" = {
       value = "$snow_name$"
    }
  }

  vars += {
    notification_type = "$notification.type$"
    notification_hostname = "$host.name$"
    notification_servicename = "$service.name$"
    notification_serviceoutput = "$service.output$"
    notification_servicestate = "$service.state$"
    notification_name= "$snow.name$"
    notification_template = "$snow.template$"
  }
}

template Notification "snow-svc-notification" {
  command = "servicenow-service-notification"

  states = [ OK, Warning, Critical, Unknown ]
  types = [ Problem, Acknowledgement, Recovery, Custom,
            FlappingStart, FlappingEnd,
            DowntimeStart, DowntimeEnd, DowntimeRemoved ]
}

apply Notification "snow" to Service {
  import "snow-svc-notification"

  users = [ "snowadmin" ]

  assign where service.vars.notification_snow
}

apply Service "snow-users" {
  import "generic-service"

  check_command = "users"

  assign where host.name == NodeName

  # max_check_attempts = 1

  vars.notification_snow = true
  vars.snow_name = "generic"
  vars.snow_template = "mytemplate"
}

object User "snowadmin" {
  display_name = "ServiceNow Admin"
  enable_notifications = true
}
